---
name: Ethan
surname: vanderWilden
position: "Doctoral Student"
address: "University of Wiscons-Madison"
phone: 978 505 9966
email: "ethan.vanderWilden@wisc.edu"
twitter: e_vanderwilden
github: evanderwilden
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::hyndman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where, ~Awards,
  "BA in Government (Honors) and Physics: Astrophysics (Distinction)", "2016-20", "Colby College", "Waterville, Maine", "Magna Cum Laude, Phi Beta Kappa, Pi Sigma Alpha (Political Science), Sigma Pi Sigma (Physics)"
) %>% 
  detailed_entries(Degree, Year, Institution, Where, Awards)
```

# Research Experience

```{r}
tribble(
  ~ Type, ~ Year, ~ Institution, ~ Project,
  "Research Assistant for Professor Jennifer Yoder", "2018", "Colby College", "Project Title: The Politics of the Past in Europe",
  "Field Research in Spain, Self-directed Honors Thesis Project", "2019", "Colby College", "Project Title: Ending the Spanish Exception: Explaining the Rise of Vox",
) %>% 
  detailed_entries(Type, Year, Institution, Project)

```

# Awards and Fellowships

```{r}
library(tibble)
tribble(
  ~ Type, ~ Year, ~ Institution, ~ Info,
  "2-Year University Fellowship", "2020-21", "University of Wisconsin-Madison", "Second year undetermined",
  "Albert A. Mavrinac Prize", "2020", "Colby College", "For Best Original Research Project in the Department of Government",
  "Cal Mackenzie Fellowship", "2019", "Colby College", "To support original undergraduate research in the Department of Government",
) %>% 
  detailed_entries(Type, Year, Institution, Info)
```

# Teaching Experience

```{r}
library(tibble)
tribble(
  ~ Type, ~ Year, ~ Institution, ~ Class, ~Instructor,
  "Teaching Assistant and Grader", "2018-20", "Colby College", "Astronomy 151: Stars, Stellar Systems, and Cosmology", "Professor Elizabeth McGrath",
  "Grader", "2019", "Colby College", "Astronomy 231: Introdcution to Astrophysics", "Professor Elizabeth McGrath",
  "Grader", "2020", "Colby College", "Astronomy 342: Galaxies and Cosmology", "Professor Dale Kocevski",
) %>% 
  detailed_entries(Type, Year, Institution, Class, Instructor)
```

# Language Skills
```{r}
library(tibble)
tribble(
  ~ Languages,
  "Experience in R, Stata, and Python",
  "Native English, Advanced Spanish", 
) %>% 
  detailed_entries(Languages)
```
